package com.nguyenduong.chatalone;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@Controller
@RestController
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserinfoRepository userRepository;

    @RequestMapping("api/data")
    public Object GetUser(){
        return userRepository.findAll();

    }
}
